### ISSUE TITLE
"Bad credentials" error when starting spotifyd

### ISSUE THREAD

**Issue by DavidHospital** [Spotifyd/spotifyd#1293]
**Description**
I've been using spotifyd for a few years now without issue. Just this morning when trying to connect, I got the following error:
```
failed to connect to spotify: Login failed with reason: Bad credentials
```
I am able to login just fine on all my other devices, it's only using `spotifyd` where I have this issue. I have also tried restarting my PC, and using my email as username instead of the username string, as suggested by https://github.com/Spotifyd/spotifyd/issues/1269, but neither have worked.

**To Reproduce**
1. start with `spotifyd --verbose --no-daemon`

**Expected behavior**
`spotifyd` should authenticate with spotify

**Logs**
<details><summary>Click to show logs</summary>

```
<!-- PLEASE PASTE YOUR LOGS BELOW THIS LINE WHEN REPORTING BUGS. Make sure to run spotifyd using the `--verbose` flag -->
<!-- They have to be betwenn the `/summary` and the `/details` HTML tags, and inside the backticks '`' -->  
Loading config from "/home/dhospital/.config/spotifyd/spotifyd.conf"
CliConfig { config_path: None, no_daemon: true, verbose: true, pid: None, shared_config: SharedConfigValues { username: Some("taken out for privacy"), username_cmd: None, password: Some("taken out for privacy"), password_cmd: None, use_keyring: false, use_mpris: None, dbus_type: None, on_song_change_hook: None, cache_path: None, no-audio-cache: false, backend: Some(Alsa), volume_controller: None, device: None, control: None, mixer: None, device_name: Some("WorkUbuntu"), bitrate: Some(Bitrate160), audio_format: None, initial_volume: Some("50"), volume_normalisation: false, normalisation_pregain: Some(-10.0), zeroconf_port: None, proxy: None, device_type: Some(Computer), autoplay: false, max_cache_size: None } }
Found user shell: Some("/bin/bash")
No proxy specified
registering event source with poller: token=Token(2147483649), interests=READABLE
Using software volume controller.
registering event source with poller: token=Token(0), interests=READABLE | WRITABLE
signal: Want
signal found waiting giver, notifying
poll_want: taker wants!
signal: Want
signal: Want
Ignoring blacklisted access point ap-gue1.spotify.com:4070
Ignoring blacklisted access point ap-gue1.spotify.com:443
Ignoring blacklisted access point ap-gue1.spotify.com:80
Connecting to AP "ap-gae2.spotify.com:443"
deregistering event source from poller
signal: Closed
registering event source with poller: token=Token(16777216), interests=READABLE | WRITABLE
deregistering event source from poller
failed to connect to spotify: Login failed with reason: Bad credentials
```

</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**

- OS:  Ubuntu 22.04.4 LTS
- Spotifyd:  0.3.5 (cargo)
- cargo:  1.79.0

**Comment by mghalix** [comment]
Got exactly the same bug just today (been working for so long now)
![image](https://github.com/user-attachments/assets/ac37a54f-e11e-4f60-b8c1-55740882fd8b)

**Comment by robbertkauffman** [comment]
Same here. It was working fine for months and stopped working this morning. Using configured username & password and have disabled zeroconf.

I believe it's an issue with librespot as I get the same error with Raspotify.

**Comment by eladyn** [comment]
Indeed something seems to have changed on the Spotify side, since I found already several reports (on several projects) which report the exact same error (most reports have been published recently). It started happening for me too, the issue persists when using the newest `librespot` dev version, so probably something that needs to be fixed upstream.

Anyway, for now what still should be working (from my tests) is discovery, so until this is fixed it might be a viable option for you?

---

Issues in other projects:

- https://github.com/librespot-org/librespot-java/issues/921
- https://github.com/kokarare1212/librespot-python/issues/277

**Comment by inkhey** [comment]
Hello all,

> Anyway, for now what still should be working (from my tests) is discovery, so until this is fixed it might be a viable option for you?

What do you mean by "discovery" ?

**Comment by dabalroman** [comment]
> What do you mean by "discovery" ?

Indeed, it still works with discovery.
To enable it, all of these values in config should be commented out.
```
#LIBRESPOT_DISABLE_DISCOVERY=
#LIBRESPOT_USERNAME=
#LIBRESPOT_PASSWORD=
```

See here: https://github.com/dtcooper/raspotify/wiki/Basic-Setup-Guide#spotify-credentials

**Comment by eladyn** [comment]
Yeah, thanks for the clarification. For `spotifyd`, you need to comment out the `username` and `password` line in the config to make it go into discovery mode.

**Comment by DavidHospital** [comment]
> See here: https://docs.spotifyd.rs/config/File.html#alternatives-to-storing-your-password-in-the-config-file
> 
> Your device will be visible in spotify app as a player (probably requires same network for devices to work).

I can't get this to work, I've commented out `username` and `password`, as well as `cache_path` and `cache_directory`. When I launch `spotifyd`, it says `Zeroconf server listening on 0.0.0.0:39127`, but none of my devices can see it on the network. Am I missing something?

**Comment by eladyn** [comment]
It might be some firewall issue? Make sure you expose the ports 5353 UDP and the one that the logs say via TCP.

**Comment by bennylb** [comment]
> > See here: https://docs.spotifyd.rs/config/File.html#alternatives-to-storing-your-password-in-the-config-file
> > Your device will be visible in spotify app as a player (probably requires same network for devices to work).
> 
> I can't get this to work, I've commented out `username` and `password`, as well as `cache_path` and `cache_directory`. When I launch `spotifyd`, it says `Zeroconf server listening on 0.0.0.0:39127`, but none of my devices can see it on the network. Am I missing something?

I had to use the official Spotify client to first authenticate with zeroconf and then spotifyd became visible to other devices on the network.

**Comment by dspearson** [comment]
FYI, as I mentioned on the librespot issue, `SpConnectionLoginZeroConf` is a mandatory implementation feature for Spotify Connect devices and the documentation for hardware implementers states that SpConnectionLoginPassword was to only be used for testing purposes --  it has in fact been [removed from the eSDK](https://developer.spotify.com/documentation/commercial-hardware/implementation/reference/3.203) and therefore I assume should never be used.

The blob obtained via ZeroConf authentication flow is **not** tied to devices on the same network currently, and so for those wishing to reduce effort or network/mDNS config issues, simply running spotifyd on the same machine as a running official client for initial device registration, and then copying the credentials obtained to a remote machine where spotifyd is to be deployed, should work just fine. At least I tested it with librespot with no issues.

**Comment by casualNavigator** [comment]
> FYI, as I mentioned on the librespot issue, `SpConnectionLoginZeroConf` is a mandatory implementation feature for Spotify Connect devices and the documentation for hardware implementers states that SpConnectionLoginPassword was to only be used for testing purposes -- it has in fact been [removed from the eSDK](https://developer.spotify.com/documentation/commercial-hardware/implementation/reference/3.203) and therefore I assume should never be used.
> 
> The blob obtained via ZeroConf authentication flow is **not** tied to devices on the same network currently, and so for those wishing to reduce effort or network/mDNS config issues, simply running spotifyd on the same machine as a running official client for initial device registration, and then copying the credentials obtained to a remote machine where spotifyd is to be deployed, should work just fine. At least I tested it with librespot with no issues.

@dspearson thanks for this, this explained why spotifyd suddenly stoped working today because of Bad Credential errors (?)

I cannot find the blob ~/.cache/spotifyd nor ~/.config/spotifyd, is it stored here?

**Comment by dspearson** [comment]
@casualNavigator unfortunately I'm not a spotifyd user but taking a brief look at the code it uses librespot's crates directly so maybe try find on ~, looking for `credentials.json`? You're typically looking for a key called `auth_data`.

**Comment by casio1983** [comment]
@casualNavigator in my case the credentials.json are stored in the cache_path location specified in config file ~/.config/spotifyd/spotifyd.conf

**Comment by mazarian** [comment]
Same issue on my end but I'm using raspotify.

**Comment by casualNavigator** [comment]
@dspearson and @casio1983  Thanks, found a `credentials.json` file for spotify_player cli (which uses librespot) in `~/.config/spotify-player/credentials.json`, and indeed contained `auth_data` but I wasn't able to use it, as I tried resetting my Spotify password trying to troubleshoot this issue. Thanks for pointing out to the right direction.

I've tried to generate the `auth_data` manually using instructions here [https://developer.spotify.com/documentation/web-api/tutorials/getting-started](url):

```bash
curl -X POST "https://accounts.spotify.com/api/token" \
     -H "Content-Type: application/x-www-form-urlencoded" \
     -d "grant_type=client_credentials&client_id=my-client-id&client_secret=my-client-secret"
```

And updated the `auth_data` value in the `credentials.json` file, unfortunately that didn't work.

**Comment by Semmu** [comment]
same issue here, and also i got an email from Spotify forcing me to change my password because they detected some "suspicious activity".

(i really hope they are not killing spotifyd and other third-party clients...)

**Comment by elliotclee** [comment]
Discovery mode worked for me after I commented 'username' and 'password' out of the config file.

**Comment by SomeoneSomewhereHow** [comment]
Discovery works, but then plays via my phone not desktop via spotify-qt.

user / password are still not working since yesterday.

**Comment by Semmu** [comment]
is there a workaround to authenticate with some saved credentials/token automatically? could spotifyd write some tokens to some file after a successful zeroconf authentication, which it could read at startup?

the reason im asking is because my spotifyd disconnects after being idle for hours ( bugreported here #903 ) for which my workaround is to monitor/poll my active devices via the API and restart the spotifyd container whenever the API thinks its gone. ( commented [here](https://github.com/Spotifyd/spotifyd/issues/903#issuecomment-1554281790) )

but since the username+password auth has been turned off on Spotify's side, whenever my container is restarted it wont belong to my account, so it will essentially get in a "bootloop" and i will need to do the zeroconf authentication each time (which is inconvenient). it would be nice if spotifyd persisted the tokens in some file which could be re-used until they are expired.

**Comment by dabalroman** [comment]
There is a file called credentials.json in cache directory. There is some kind of key inside alongside username. Check if that directory is not wiped out on docker down action. It works for at least couple of hours and it's visible in spotify app after device restart. I compiled Spotifyd from source, it's running a system service under Ubuntu.

**Comment by dspearson** [comment]
You can use the cached discovery credentials for a long time. I've used mine for weeks now. Like previously mentioned, just make sure they're not deleted in your workflow.

**Comment by jolo2486** [comment]
Same or similar problem here with spotifyd 0.3.5 on Ubuntu 22.04.4:
```
$ spotifyd --no-daemon --verbose --username redacted --password redacted --backend pulseaudio --debug-credentials

No config file specified. Running with default values
CliConfig { config_path: None, no_daemon: true, verbose: true, pid: None, shared_config: SharedConfigValues { username: Some(redacted), username_cmd: None, password: Some(redacted), password_cmd: None, use_keyring: false, use_mpris: None, dbus_type: None, on_song_change_hook: None, cache_path: None, no-audio-cache: false, backend: Some(PulseAudio), volume_controller: None, device: None, control: None, mixer: None, device_name: None, bitrate: None, audio_format: None, initial_volume: None, volume_normalisation: false, normalisation_pregain: None, zeroconf_port: None, proxy: None, device_type: None, autoplay: false, max_cache_size: None } }
Found user shell: Some("/bin/bash")
No proxy specified
Using software volume controller.
Ignoring blacklisted access point ap-gew4.spotify.com:4070
Ignoring blacklisted access point ap-gew4.spotify.com:443
Ignoring blacklisted access point ap-gew4.spotify.com:80
Ignoring blacklisted access point ap-gue1.spotify.com:443
Failed to resolve Access Point: Unable to resolve any viable access points.
Using fallback "ap.spotify.com:443"
Connecting to AP "ap.spotify.com:443"
failed to connect to spotify: Login failed with reason: Bad credentials
```

I also tried discovery mode by commenting out username and password in spotifyd.conf, but it seems to be stuck:

```
$ spotifyd --no-daemon --verbose

Loading config from "/home/mrredacted/.config/spotifyd/spotifyd.conf"
CliConfig { config_path: None, no_daemon: true, verbose: true, pid: None, shared_config: SharedConfigValues { username: None, username_cmd: None, password: None, password_cmd: None, use_keyring: false, use_mpris: None, dbus_type: None, on_song_change_hook: Some("command_to_run_on_playback_events"), cache_path: Some("cache_directory"), no-audio-cache: true, backend: Some(Alsa), volume_controller: Some(Alsa), device: Some("alsa_audio_device"), control: Some("alsa_audio_device"), mixer: Some("PCM"), device_name: Some("redacted"), bitrate: Some(Bitrate160), audio_format: Some(S16), initial_volume: Some("90"), volume_normalisation: true, normalisation_pregain: Some(-10.0), zeroconf_port: Some(1234), proxy: None, device_type: Some(Speaker), autoplay: true, max_cache_size: Some(1000000000) } }
Found user shell: Some("/bin/bash")
No username specified. Checking username_cmd
No username_cmd specified
No password specified. Checking password_cmd
No password_cmd specified
No proxy specified
Using alsa volume controller.
no usable credentials found, enabling discovery
Using device id 'a35baa7bd3fe13630f66325b0b734cfc0c7cdeec'
Zeroconf server listening on 0.0.0.0:1234
found interface Interface { name: "eno1", addr: V4(Ifv4Addr { ip: 192.168.1.177, netmask: 255.255.255.0, broadcast: Some(192.168.1.255) }) }
sending packet to 224.0.0.251:5353
found interface Interface { name: "eno1", addr: V4(Ifv4Addr { ip: 192.168.1.177, netmask: 255.255.255.0, broadcast: Some(192.168.1.255) }) }
sending packet to [ff02::fb]:5353
received packet from 192.168.1.177:5353
received packet from 192.168.1.177:5353 with no query
received packet from 192.168.1.177:5353
received packet from 192.168.1.177:5353 with no query
received packet from [fe80::aeca:908d:27:dd69%2]:5353
received packet from [fe80::aeca:908d:27:dd69%2]:5353 with no query
received packet from [fe80::aeca:908d:27:dd69%2]:5353
received question: IN _ipps._tcp.local
received question: IN _ipp._tcp.local
received packet from 192.168.1.177:5353
received question: IN _ipps._tcp.local
received question: IN _ipp._tcp.local
_
```
and it just stays there (+10 min), nothing happens, and I have to interrupt the process.

I've n-ple (n>>2) checked the username and password as well as tried both with conf and CLI (-u, -p) with and without " and/or '. I also changed/updated my spotify password and it has no "problematic" characters such as spaces or ".

**Comment by dspearson** [comment]
For those that seem to have issues creating the credentials.json file, I have created the following: https://github.com/dspearson/librespot-auth

Build with `cargo build --release` (requires rust compiler/toolkit, see https://rustup.rs/). See `--help` for options. Example usage:

```
❯ ./target/release/librespot-auth --name "Example Speaker"
Open Spotify and select output device: Example Speaker
Credentials saved: credentials.json
```

**Comment by Mike-de-bike** [comment]
> For those that seem to have issues creating the credentials.json file, I have created the following: https://github.com/dspearson/librespot-auth
> 
> Build with `cargo build --release` (requires rust compiler/toolkit, see https://rustup.rs/). Example usage:
> 
> ```
> ❯ ./target/release/librespot-auth --name "Example Speaker"
> Open Spotify and select output device: Example Speaker
> Credentials saved: credentials.json
> ```

is that using of a manually created credentials.json a workaround to get spotifyd in zeroconf mode running? Has someone positive results in using it?

**Comment by MarekLew** [comment]
> For those that seem to have issues creating the credentials.json file, I have created the following: https://github.com/dspearson/librespot-auth
> 
> Build with `cargo build --release` (requires rust compiler/toolkit, see https://rustup.rs/). Example usage:
> 
> ```
> ❯ ./target/release/librespot-auth --name "Example Speaker"
> Open Spotify and select output device: Example Speaker
> Credentials saved: credentials.json
> ```

It works. After confirming authorization for "Example Speaker" in the spotify client, copy the generated `credentials.json` file to the `cache_patch` location saved in the `~/.config/spotifyd/spotifyd.conf` file, e.g. `~/.cache/spotifyd` .

**Comment by casualNavigator** [comment]
@dspearson Worked, flawlessly! Built it in Rust to too, what an absolute Chadman!

@Mike-de-bike Confirmed working, was able to use spotifyd and spotify-player again.

**Comment by trames57** [comment]
Just wanted to add here #1285  that if you have 2 IP address on your interface you may have issues with discovery.

**Comment by dspearson** [comment]
Good catch. I'm going to try and fix that in my utility right now, because it stems from the default librespot behaviour. Unexpected for sure.

**Comment by Mike-de-bike** [comment]
> @dspearson Worked, flawlessly! Built it in Rust to too, what an absolute Chadman!
> 
> @Mike-de-bike Confirmed working, was able to use spotifyd and spotify-player again.

Confirming merely, that it works using the version 0.1 of libresport auth! spotfiyd runs in docker container on aarch64 Ubuntu20.04. Credentials file is written magically in cache dir. Great commmendation for @dspearson !

**Comment by SomeoneSomewhereHow** [comment]
> For those that seem to have issues creating the credentials.json file, I have created the following: https://github.com/dspearson/librespot-auth
> 
> Build with `cargo build --release` (requires rust compiler/toolkit, see https://rustup.rs/). Example usage:
> 
> ```
> ❯ ./target/release/librespot-auth --name "Example Speaker"
> Open Spotify and select output device: Example Speaker
> Credentials saved: credentials.json
> ```

Many thanks for coding that. Really appreciated. Kudos.

I couldn't get spotifyd with FreeBSD recognising credentials.json, but is working with librespot which too works with spotify-qt. Normality resolved.

**Comment by MattGesicki** [comment]
Hi guys,
It happened to me on RPi and Raspotify. When I reinstalled latest Raspotify, service is running. Once configuring username and password in /etc/rapotify/config I got the same error about bad credentials.
Can you please advise if above step with librespot-auth would do the trick? Do I need to install Spotify desktop version, log in and find credentails.json?

**Comment by dabalroman** [comment]
> Hi guys, It happened to me on RPi and Raspotify. When I reinstalled latest Raspotify, service is running. Once configuring username and password in /etc/rapotify/config I got the same error about bad credentials. Can you please advise if above step with librespot-auth would do the trick? Do I need to install Spotify desktop version, log in and find credentails.json?

For raspotify you must enable zeroconf first, there is a key for that in config file. This mode should create credentials itself, the [librespot-auth](https://github.com/dspearson/librespot-auth) is a fallback when zeroconf does not work as expected.

Look for these in `/etc/raspotify/conf`, all should be commented out:
```
# LIBRESPOT_DISABLE_CREDENTIAL_CACHE=
# LIBRESPOT_DISABLE_DISCOVERY=
#LIBRESPOT_USERNAME=""
#LIBRESPOT_PASSWORD=""
```

**Comment by IdoEsports** [comment]
MacOS Sonoma 14.4 and spotifyd version 0.3.5.

Hey,

I used [librespot-auth](https://github.com/dspearson/librespot-auth) to generate the credentials.json and made sure to place it in the right cache directory. But for some reason, "no usable credentials found" like this:
```
~/.config/spotifyd ➜ spotifyd --no-daemon

Loading config from "/Users/abhijeetsurakanti/.config/spotifyd/spotifyd.conf"
No password specified. Checking password_cmd
No password_cmd specified
No proxy specified
Using software volume controller.
no usable credentials found, enabling discovery
error sending packet Os { code: 65, kind: HostUnreachable, message: "No route to host" }
```

I've confirmed that the credentials.json file is being read by including syntax erros which were caught like this:
```
~/.config/spotifyd ➜ spotifyd --no-daemon

Loading config from "/Users/abhijeetsurakanti/.config/spotifyd/spotifyd.conf"
No password specified. Checking password_cmd
No password_cmd specified
No proxy specified
Using software volume controller.
Error reading credentials from cache: expected `,` or `}` at line 5 column 2
no usable credentials found, enabling discovery
error sending packet Os { code: 65, kind: HostUnreachable, message: "No route to host" }
```

As for the:
`error sending packet Os { code: 65, kind: HostUnreachable, message: "No route to host" }`
I believe it is related to #1026 which hasn't given me much trouble in the past because it only shows up in discovery mode.

This made me wonder if the credentials were valid so I copied the credentials.json file over to the cache folder of [spotify-player](https://github.com/aome510/spotify-player). I was facing the same "Bad credentials" error for spotify-player as well and the new credentials.json file actually ended up solving the error and I'm able to use it like regular.

I appreciate any help and also great work building this thread so far.

**Comment by eladyn** [comment]
Thanks to everyone who is helping to work around this issue!

For a `spotifyd`-only solution, you can do the following:

1. Set `cache_path` to a writable directory (e.g. `/home/user/.cache/spotifyd`).
2. Start `spotifyd` in discovery mode (by commenting all the `username`, `username_cmd`, ... options). You should see the line `no usable credentials found, enabling discovery` in your logs.
3. Connect with any of the official clients to `spotifyd` (which has to be on the same network).
4. Stop `spotifyd`. Make sure that in the cache directory that you set before, there is now a file called `credentials.json`.
5. To make `spotifyd` use that file, we have to provide it with the correct username which can be found in `credentials.json`. (Set the `username` option to the username that can be found in `credentials.json`.)
6. Start `spotifyd` again, it should now authenticate successfully (and not enter discovery mode!)

*Note*: Instead of step 5, you can also use the following very clean solution: Set the option `username_cmd = "jq -r .username /yourcachedirectory/credentials.json"`. This will automatically retrieve the correct username from `credentials.json` so you can just clear the cache to connect to someone else's account.

**Comment by DavidHospital** [comment]
> Thanks to everyone who is helping to work around this issue!
> 
> For a `spotifyd`-only solution, you can do the following:
> 
>     1. Set `cache_path` to a writable directory (e.g. `/home/user/.cache/spotifyd`).
> 
>     2. Start `spotifyd` in discovery mode (by commenting all the `username`, `username_cmd`, ... options). You should see the line `no usable credentials found, enabling discovery` in your logs.
> 
>     3. Connect with any of the official clients to `spotifyd` (which has to be on the same network).
> 
>     4. Stop `spotifyd`. Make sure that in the cache directory that you set before, there is now a file called `credentials.json`.
> 
>     5. To make `spotifyd` use that file, we have to provide it with the correct username which can be found in `credentials.json`. (Set the `username` option to the username that can be found in `credentials.json`.)
> 
>     6. Start `spotifyd` again, it should now authenticate successfully (and not enter discovery mode!)
> 
> 
> _Note_: Instead of step 5, you can also use the following very clean solution: Set the option `username_cmd = "jq -r .username /yourcachedirectory/credentials.json"`. This will automatically retrieve the correct username from `credentials.json` so you can just clear the cache to connect to someone else's account.

After step 4, I don't have a `credentials.json` in my cache directory, other files are being created there though, so the cache location is working. Any idea why that wouldn't be created?

**Comment by Semmu** [comment]
Same here, no `credentials.json` gets created after enabling the cache and authenticating via zeroconf 😕

**Comment by mghalix** [comment]
> Thanks to everyone who is helping to work around this issue!
> 
> For a `spotifyd`-only solution, you can do the following:
> 
>     1. Set `cache_path` to a writable directory (e.g. `/home/user/.cache/spotifyd`).
> 
>     2. Start `spotifyd` in discovery mode (by commenting all the `username`, `username_cmd`, ... options). You should see the line `no usable credentials found, enabling discovery` in your logs.
> 
>     3. Connect with any of the official clients to `spotifyd` (which has to be on the same network).
> 
>     4. Stop `spotifyd`. Make sure that in the cache directory that you set before, there is now a file called `credentials.json`.
> 
>     5. To make `spotifyd` use that file, we have to provide it with the correct username which can be found in `credentials.json`. (Set the `username` option to the username that can be found in `credentials.json`.)
> 
>     6. Start `spotifyd` again, it should now authenticate successfully (and not enter discovery mode!)
> 
> 
> _Note_: Instead of step 5, you can also use the following very clean solution: Set the option `username_cmd = "jq -r .username /yourcachedirectory/credentials.json"`. This will automatically retrieve the correct username from `credentials.json` so you can just clear the cache to connect to someone else's account.


This solved it for me, thanks!

**Comment by MattGesicki** [comment]
> For raspotify you must enable zeroconf first, there is a key for that in config file. This mode should create credentials itself, the [librespot-auth](https://github.com/dspearson/librespot-auth) is a fallback when zeroconf does not work as expected.
> 
> Look for these in `/etc/raspotify/conf`, all should be commented out:
> 
> ```
> # LIBRESPOT_DISABLE_CREDENTIAL_CACHE=
> # LIBRESPOT_DISABLE_DISCOVERY=
> #LIBRESPOT_USERNAME=""
> #LIBRESPOT_PASSWORD=""
> ```

That worked without any stuff with credentials.json, thanks!

**Comment by Moltey** [comment]
> Thanks to everyone who is helping to work around this issue!
> 
> For a `spotifyd`-only solution, you can do the following:
> 
>     1. Set `cache_path` to a writable directory (e.g. `/home/user/.cache/spotifyd`).
> 
>     2. Start `spotifyd` in discovery mode (by commenting all the `username`, `username_cmd`, ... options). You should see the line `no usable credentials found, enabling discovery` in your logs.
> 
>     3. Connect with any of the official clients to `spotifyd` (which has to be on the same network).
> 
>     4. Stop `spotifyd`. Make sure that in the cache directory that you set before, there is now a file called `credentials.json`.
> 
>     5. To make `spotifyd` use that file, we have to provide it with the correct username which can be found in `credentials.json`. (Set the `username` option to the username that can be found in `credentials.json`.)
> 
>     6. Start `spotifyd` again, it should now authenticate successfully (and not enter discovery mode!)
> 
> 
> _Note_: Instead of step 5, you can also use the following very clean solution: Set the option `username_cmd = "jq -r .username /yourcachedirectory/credentials.json"`. This will automatically retrieve the correct username from `credentials.json` so you can just clear the cache to connect to someone else's account.

From one day to another, spotifyd stopped working for me with plain text credentials. You advice helped me. Thank you so much!

For those who also are working in a container that does not have 'jq' available, you may want to go the 'grep' way in 'spotifyd.conf':

```bash
[global]
zeroconf_port = 33797
cache_path = "/var/yourcachedirectory"
username_cmd = "grep -oP '(?<=\"username\":\")[^\"]*' /var/yourcachedirectory/credentials.json"
no_audio_cache = true
```

**Comment by Rockandrolljunkie** [comment]
Man, you just saved my life. Thank you so much! Much safer option too...

**Comment by SanskritFritz** [comment]
I'm trying to set zeroconf-port in `.config/spotifyd/spotifyd.conf` to set the listen port to a fixed value:
```
[global]
zeroconf-port = 38953
```
However it has no effect, while this works:

`spotifyd --no-daemon --zeroconf-port 38953`

I can't set zeroconf-port in the conf file?

**Comment by luke-barnett** [comment]
After transitioning and capturing a working credentials.json file, my Spotify account had it's password rotated again by Spotify after detecting "suspicious activity".

I'm assuming that this may have just been bad timing (I forgot to disable the service and so it would have been trying to connect constantly), but before I jump through the hoops again, I'm guessing that no one else is experiencing this and after cleanly transitioning to a credentials.json file it keeps working (at least for a while until the token eventually expires?).

**Comment by Montero1905** [comment]
> Thanks to everyone who is helping to work around this issue!
> 
> For a `spotifyd`-only solution, you can do the following:
> 
> 1. Set `cache_path` to a writable directory (e.g. `/home/user/.cache/spotifyd`).
> 2. Start `spotifyd` in discovery mode (by commenting all the `username`, `username_cmd`, ... options). You should see the line `no usable credentials found, enabling discovery` in your logs.
> 3. Connect with any of the official clients to `spotifyd` (which has to be on the same network).
> 4. Stop `spotifyd`. Make sure that in the cache directory that you set before, there is now a file called `credentials.json`.
> 5. To make `spotifyd` use that file, we have to provide it with the correct username which can be found in `credentials.json`. (Set the `username` option to the username that can be found in `credentials.json`.)
> 6. Start `spotifyd` again, it should now authenticate successfully (and not enter discovery mode!)
> 
> _Note_: Instead of step 5, you can also use the following very clean solution: Set the option `username_cmd = "jq -r .username /yourcachedirectory/credentials.json"`. This will automatically retrieve the correct username from `credentials.json` so you can just clear the cache to connect to someone else's account.

There are is no 'credentials.json' file in the cache directory after stopping spotifyd. Is there another way to get the credentials.json file? I'm working on MacOS.

**Comment by SomeoneSomewhereHow** [comment]
You can generate a credentials.json file as instructed by this comment.

https://github.com/Spotifyd/spotifyd/issues/1293#issuecomment-2293136285

**Comment by Isaac-Leonard** [comment]
Trying to run in descovery mode with the username and password_cmd fields commented out in my config seems to run but gives me this error:
sending packet to [ff02::fb]:5353
error sending packet Os { code: 65, kind: HostUnreachable, message: "No route to host" }

Which seems to be related to ipv6, this error is mentioned in an older issue but it was concluded that it should only be an issue on ipv6 only networks, which I'm not on.
Spotifyd isn't showing up on my local network however so I'm not sure how to generate a fresh credentials.json file.

**Comment by Bklyn97** [comment]
I'm experiencing the same "Bad credentials" issue when starting spotifyd on Arch Linux. I’ve double-checked my username and password, and they are correct. Here's what I’ve tried so far:

    Used both my Spotify username and email address as the username.
    Tried entering credentials directly in the command line and in the spotifyd.conf file.
    Removed the cache and config files, then retried with fresh setup.
    Attempted running in discovery mode by commenting out the username and password fields in the config file.

Despite all this, I continue to receive the "Login failed with reason: Bad credentials" error.

**Comment by SomeoneSomewhereHow** [comment]
@Isaac-Leonard
@Bklyn97
@Montero1905 

You can generate a credentials.json file as instructed by this comment.
https://github.com/Spotifyd/spotifyd/issues/1293#issuecomment-2293136285

Repo:
https://github.com/dspearson/librespot-auth

> For those that seem to have issues creating the credentials.json file, I have created the following: https://github.com/dspearson/librespot-auth
> 
> Build with `cargo build --release` (requires rust compiler/toolkit, see https://rustup.rs/). Example usage:
> 
> ```
> ❯ ./target/release/librespot-auth --name "Example Speaker"
> Open Spotify and select output device: Example Speaker
> Credentials saved: credentials.json
> ```




and then:


> Thanks to everyone who is helping to work around this issue!
> 
> For a `spotifyd`-only solution, you can do the following:
> 
>     1. Set `cache_path` to a writable directory (e.g. `/home/user/.cache/spotifyd`).
> 
>     2. Start `spotifyd` in discovery mode (by commenting all the `username`, `username_cmd`, ... options). You should see the line `no usable credentials found, enabling discovery` in your logs.
> 
>     3. Connect with any of the official clients to `spotifyd` (which has to be on the same network).
> 
>     4. Stop `spotifyd`. Make sure that in the cache directory that you set before, there is now a file called `credentials.json`.
> 
>     5. To make `spotifyd` use that file, we have to provide it with the correct username which can be found in `credentials.json`. (Set the `username` option to the username that can be found in `credentials.json`.)
> 
>     6. Start `spotifyd` again, it should now authenticate successfully (and not enter discovery mode!)
> 
> 
> _Note_: Instead of step 5, you can also use the following very clean solution: Set the option `username_cmd = "jq -r .username /yourcachedirectory/credentials.json"`. This will automatically retrieve the correct username from `credentials.json` so you can just clear the cache to connect to someone else's account.

**Comment by Isaac-Leonard** [comment]
@SomeoneSomewhereHow I tried running the code at https://github.com/dspearson/librespot-auth but the device still doesn't show up in the webplayer or on my phone as available to connect to.
I suspect it may be related to my wifi, I can either try connect over my universities wifi which does some funky stuff with their ip addresses and so the server may not be broadcasting.
I've also tried connecting with my phone hotspot however and stil no luck.

**Comment by Isaac-Leonard** [comment]
Okay, I got it to work, it only shows up in the spotify desk top app

**Comment by fgordilloz** [comment]
> For those that seem to have issues creating the credentials.json file, I have created the following: https://github.com/dspearson/librespot-auth
> 
> Build with `cargo build --release` (requires rust compiler/toolkit, see https://rustup.rs/). Example usage:
> 
> ```
> ❯ ./target/release/librespot-auth --name "Example Speaker"
> Open Spotify and select output device: Example Speaker
> Credentials saved: credentials.json
> ```

After creating the credentials file, leaving it where it should be and keeping the username and password values ​​in spotifyd.conf, everything worked again.

Thank you very much, @dspearson 

After

**Comment by eladyn** [comment]
> After step 4, I don't have a `credentials.json` in my cache directory, other files are being created there though, so the cache location is working. Any idea why that wouldn't be created?

Oh, I'm sorry totally forgot about that. The latest release `v0.3.5` accidentally disabled credential caching. It has been re-enabled on master, but has not made it to release yet. So this workaround only works on pre 0.3.5 or on the latest master.

**Comment by einalex** [comment]
> > Thanks to everyone who is helping to work around this issue!
> > For a `spotifyd`-only solution, you can do the following:
> > ```
> > 1. Set `cache_path` to a writable directory (e.g. `/home/user/.cache/spotifyd`).
> > 
> > 2. Start `spotifyd` in discovery mode (by commenting all the `username`, `username_cmd`, ... options). You should see the line `no usable credentials found, enabling discovery` in your logs.
> > 
> > 3. Connect with any of the official clients to `spotifyd` (which has to be on the same network).
> > 
> > 4. Stop `spotifyd`. Make sure that in the cache directory that you set before, there is now a file called `credentials.json`.
> > 
> > 5. To make `spotifyd` use that file, we have to provide it with the correct username which can be found in `credentials.json`. (Set the `username` option to the username that can be found in `credentials.json`.)
> > 
> > 6. Start `spotifyd` again, it should now authenticate successfully (and not enter discovery mode!)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > _Note_: Instead of step 5, you can also use the following very clean solution: Set the option `username_cmd = "jq -r .username /yourcachedirectory/credentials.json"`. This will automatically retrieve the correct username from `credentials.json` so you can just clear the cache to connect to someone else's account.
> 
> From one day to another, spotifyd stopped working for me with plain text credentials. You advice helped me. Thank you so much!
> 
> For those who also are working in a container that does not have 'jq' available, you may want to go the 'grep' way in 'spotifyd.conf':
> 
> ```shell
> [global]
> zeroconf_port = 33797
> cache_path = "/var/yourcachedirectory"
> username_cmd = "grep -oP '(?<=\"username\":\")[^\"]*' /var/yourcachedirectory/credentials.json"
> no_audio_cache = true
> ```

Setting the zeroconf_port to a higher number allowed this to work for me.

**Comment by Semmu** [comment]
> > After step 4, I don't have a `credentials.json` in my cache directory, other files are being created there though, so the cache location is working. Any idea why that wouldn't be created?
> 
> Oh, I'm sorry totally forgot about that. The latest release `v0.3.5` accidentally disabled credential caching. It has been re-enabled on master, but has not made it to release yet. So this workaround only works on pre 0.3.5 or on the latest master.

ohh wow, this was the key for me, i downgraded to v0.3.4 and now the credentials caching works and finally i dont have to manually reauthenticate via zeroconf every time i restart the container! thanks!

**Comment by eladyn** [comment]
Thanks for the confirmation. Maybe a new release would make sense, especially regarding some other issues.

**Comment by takase1121** [comment]
> > > After step 4, I don't have a `credentials.json` in my cache directory, other files are being created there though, so the cache location is working. Any idea why that wouldn't be created?
> > 
> > 
> > Oh, I'm sorry totally forgot about that. The latest release `v0.3.5` accidentally disabled credential caching. It has been re-enabled on master, but has not made it to release yet. So this workaround only works on pre 0.3.5 or on the latest master.
> 
> ohh wow, this was the key for me, i downgraded to v0.3.4 and now the credentials caching works and finally i dont have to manually reauthenticate via zeroconf every time i restart the container! thanks!

I was able to downgrade by `chmod 400 credentials.json`. This is definitely a temporary fix but it will prevent spotifyd running as the user from ever removing the file.

**Comment by aurimarapsilva** [comment]
> > For those that seem to have issues creating the credentials.json file, I have created the following: https://github.com/dspearson/librespot-auth
> > Build with `cargo build --release` (requires rust compiler/toolkit, see https://rustup.rs/). Example usage:
> > ```
> > ❯ ./target/release/librespot-auth --name "Example Speaker"
> > Open Spotify and select output device: Example Speaker
> > Credentials saved: credentials.json
> > ```
> 
> It works. After confirming authorization for "Example Speaker" in the spotify client, copy the generated `credentials.json` file to the `cache_patch` location saved in the `~/.config/spotifyd/spotifyd.conf` file, e.g. `~/.cache/spotifyd` .

For now it works for me, thank you very much!

**Comment by mrhappyma** [comment]
I also had this issue. Several hours after, I was signed out of Spotify on all devices, and got an email telling me I need to set a new password “due to detected suspicious activity”.

**Comment by dabalroman** [comment]
> anyone know any alternatives that download natively from spotify and actually work since the removed password auth?

You can use librespot. On the project page you'll find instalation and configuration instructions.

**Comment by ivoshm** [comment]
> anyone know any alternatives that download natively from spotify and actually work since the removed password auth?

I'm afraid the only way to finally solve this problem in spotifyd is to switch to OAuth authentication (as librespot already did in dev branch).

**Comment by makzef** [comment]
> For those that seem to have issues creating the credentials.json file, I have created the following: https://github.com/dspearson/librespot-auth
> 
> Build with `cargo build --release` (requires rust compiler/toolkit, see https://rustup.rs/). Example usage:
> 
> ```
> ❯ ./target/release/librespot-auth --name "Example Speaker"
> Open Spotify and select output device: Example Speaker
> Credentials saved: credentials.json
> ```

Nope, not working. Tried to use provided librespot package, tried build it myself. Spotify app doesn't see any devices, through it only shows other devices with official clients.

**Comment by makzef** [comment]
> > For those that seem to have issues creating the credentials.json file, I have created the following: https://github.com/dspearson/librespot-auth
> > Build with `cargo build --release` (requires rust compiler/toolkit, see https://rustup.rs/). Example usage:
> > ```
> > ❯ ./target/release/librespot-auth --name "Example Speaker"
> > Open Spotify and select output device: Example Speaker
> > Credentials saved: credentials.json
> > ```
> 
> Nope, not working. Tried to use provided librespot package, tried build it myself. Spotify app doesn't see any devices, through it only shows other devices with official clients.

After some time, I remembered that similar issues were due to the firewall. And this was mentioned above. I didn't know which port librespot-auth uses, or is it require something else. So, I just stopped `firewalld.service` temporarily and spotify client finaly showed a new device. Then I managed to generate `credentials.json`. 

So anyone having problems with missing devices in spotify client, better check firewall setting.

Thank you.

**Comment by Jorpy76** [comment]
Hello, thank you! I followed the steps, and it finally started working again.

**Comment by hadronized** [comment]
I don’t have a native Spotify client, and going through the Web browser doesn’t see the output device. I feel I’m stuck. :(

**Comment by fgordilloz** [comment]
> ~I don’t have a native Spotify client, and going through the Web browser doesn’t see the output device. I feel I’m stuck. :(~
> 
> EDIT: nevermind, I was able to do it with the phone as I’m on the same network.

![image](https://github.com/user-attachments/assets/367d6eb9-3939-489f-8bf6-2c9fd53745bc)

From Spotify Web Player you can view devices

**Comment by hadronized** [comment]
> > ~I don’t have a native Spotify client, and going through the Web browser doesn’t see the output device. I feel I’m stuck. :(~
> > EDIT: nevermind, I was able to do it with the phone as I’m on the same network.
> 
> ![image](https://private-user-images.githubusercontent.com/12462986/377019582-367d6eb9-3939-489f-8bf6-2c9fd53745bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxMTY5ODAsIm5iZiI6MTcyOTExNjY4MCwicGF0aCI6Ii8xMjQ2Mjk4Ni8zNzcwMTk1ODItMzY3ZDZlYjktMzkzOS00ODlmLThiZjYtMmM5ZmQ1Mzc0NWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDIyMTEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkYzcyOTJlYWIwZTMwOWY3NDE1ZWE1YmU4MTYyOTcxYjQyZjI0OGZiMDM5YTI5YTYyYjRhNWEwZjI0YzA1ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kMtumx8dVz8bSQHFFQVQheLuL0b6yfMsk66xbU-4b70)
> 
> From Spotify Web Player you can view devices

I know, and it wasn’t showing up there; I really had to go through my phone to get it. I’m not sure why, at least it worked. :)

**Comment by 0323pin** [comment]
FWIW, `librespot`-0.5.0 was released yesterday and this is fixed.

**Comment by gbwebdev** [comment]
> FWIW, `librespot`-0.5.0 was released yesterday and this is fixed.

I simply tried to rebuild spotifyd after changing the "0.4" to "0.5" for librespot dependencies in the Cargo.toml (hey, it was worth a shot), but it does not work...
I am not surprised of course, but it means that librespot does not use semantic versioning.

Meanwhile, I'm affraid the solution won't come from me : I never wrote a single line of Rust and I gave pretty much everything I got on this "search and replace" in the Cargo.toml ;-)

**Comment by eladyn** [comment]
Just a quick heads up: I'm basically done with bumping librespot to the new version, just some dbus MPRIS stuff is still missing, where I'm working on getting rid of the web API requests completely. I hope to get it done within the next couple of days, however if you'd like to help testing or can't wait (and don't need DBus for your setup), I published the current state [here](https://github.com/eladyn/spotifyd/tree/deps_upgrade).
Also, OAuth is **still** not implemented in `spotifyd`, but it should be available soon.

**Comment by dataCobra** [comment]
Tried the branch you recommended but I sadly still get the "bad credentials" error.

**Comment by eladyn** [comment]
Yes, the broken user-password auth is still the one used in that branch (the new OAuth way needs to be adapted from upstream first).

**Comment by GardenerGeralt** [comment]
Hi @eladyn thank you for working on this issue. When do you think the fixed version will come to Arch packages?

**Comment by eladyn** [comment]
Usually, Arch should be quite fast, once we release the new version. But since that hasn't happened yet, it'll take a couple of days at least before that.

**Comment by poetex** [comment]
Bumping this issue. I have tried everything in this thread and still cannot resolve the Bad Credentials error.

**Comment by citosid** [comment]
I've never used it before so I don't have a credentials file, and I tried creating one but it does not like the format. Does anyone has an example of the shape of the json file?

**Comment by RazoBeckett** [comment]
> I've never used it before so I don't have a credentials file, and I tried creating one but it does not like the format. Does anyone has an example of the shape of the json file?

{"username":"redacted","auth_type":1,"auth_data":"redacted"}

**Comment by RazoBeckett** [comment]
if someone have fixed this issue or solved it help me get it working please

**Comment by MiuKaShi** [comment]
> if someone have fixed this issue or solved it help me get it working please

Here, I found a simple way to solve this problem with https://github.com/aome510/spotify-player. Hope it helps.

1. Install and open `spotify-player`, after finishing authentication, the `credentials.json ` will be created in  `~/.cache/spotify-player`
2. Set cache_path and username_cmd in spotifyd.conf as follows
```
cache_path = "/home/user_name/.cache/spotifyd"
username_cmd = "/usr/bin/cp /home/user_name/.cache/spotify-player/credentials.json /home/user_name/.cache/spotifyd && jq -r .username /home/user_name/.cache/spotify-player/credentials.json"
# password = ""
```
Now, run `spotifyd --no-daemon --verbose` it should show that the authentication is successful. You can use `spotify-player` as a TUI player.

**Comment by kingofsquirrel** [comment]
I've also just encountered this issue and when trying to solve it by using zeroconf. So I basically just left my username and password field blank and to my understanding, the first client that connects basically passes on it's saved credentials.

However, when I tried to connect to the device, the addon crashed and I got this error: 

`Connection failed: Cannot create session: Connection refused (os error 111)`

I solved it by adding this line to /etc/hosts

`0.0.0.0 apresolve.spotify.com`

No idea if this helps anyone, just thought I'd mention it.

**Comment by CompeyDev** [comment]
> > if someone have fixed this issue or solved it help me get it working please
> 
> Here, I found a simple way to solve this problem with [aome510/spotify-player](https://github.com/aome510/spotify-player?rgh-link-date=2024-12-11T09%3A32%3A30Z). Hope it helps.
> 
>     1. Install and open `spotify-player`, after finishing authentication, the `credentials.json ` will be created in  `~/.cache/spotify-player`
> 
>     2. Set cache_path and username_cmd in spotifyd.conf as follows (replace user_name with your name)
> 
> 
> ```
> cache_path = "/home/user_name/.cache/spotifyd"
> username_cmd = "cp /home/user_name/.cache/spotify-player/credentials.json /home/user_name/.cache/spotifyd && jq -r .username /home/user_name/.cache/spotifyd/credentials.json"
> # password = ""
> ```
> 
> Now, run `spotifyd --no-daemon --verbose` it should show that the authentication is successful. You can use `spotify-player` as a TUI player.

Heads up -- this misses a trailing `/` and hence copies it to a file.

```diff
- username_cmd = "cp /home/user_name/.cache/spotify-player/credentials.json /home/user_name/.cache/spotifyd && jq -r .username /home/user_name/.cache/spotifyd/credentials.json"
+ username_cmd = "cp /home/user_name/.cache/spotify-player/credentials.json /home/user_name/.cache/spotifyd/ && jq -r .username /home/user_name/.cache/spotifyd/credentials.json"
```

**Comment by CompeyDev** [comment]
Trying the workaround, I'm able to get quite far, however ultimately I'm getting this error:

```
Resolve access points error: Service unavailable { client error (Connect) }
Connecting to AP "ap.spotify.com:443"
unknown subscription uri=hm://pusher/v1/connections/REDACTED
response pushed over Mercury: MercuryResponse { uri: "hm://pusher/v1/connections/REDACTED", status_code: 200, payload: [] }
could not dispatch command: Service unavailable { error handling Mercury response: MercuryResponse { uri: "hm://pusher/v1/connections/REDACTED", status_code: 200, payload: [] } }
Authenticating with AP using AUTHENTICATION_STORED_SPOTIFY_CREDENTIALS
Authenticated as 'UID' !
failed to connect to spotify: Service unavailable { Session is not connected }
```

**Comment by Boxer66** [comment]
I also had some problems with this. Usually I use ncspot for my spotify needs but it doesn´t work properly atm so I had to install spotifyd.

I got it working with a combination of solutions provided here.
I use librespot 0.60 on a EndeavourOS laptop with i3-wm. I am a spotify premium user.

1. Edit /etc/hosts and add this line 
0.0.0.0 apresolve.spotify.com

3. Create the ~/.cache/spotifyd folder

4. install and start spotify-player to create credentials.json 

5.  Set cache_path and username_cmd in spotifyd.conf as follows (replace user_name with your name) 

cache_path = "/home/user_name/.cache/spotifyd"
username_cmd = "cp /home/user_name/.cache/spotify-player/credentials.json /home/user_name/.cache/spotifyd/  && jq -r .username /home/user_name/.cache/spotifyd/credentials.json" and comment out password = ""

6.  run spotifyd --no-daemon --verbose
7. You can now use spotify-player or in my case I use spotify-tui
8. I also edited spotifyd.conf and commented out use-keyring  and password_cmd

Thanks to  [MiuKaShi](https://github.com/MiuKaShi), [kingofsquirrel](https://github.com/kingofsquirrel) and [CompeyDev](https://github.com/CompeyDev)


![2024-12-26-07_41_46-screenshot](https://github.com/user-attachments/assets/2bc02496-a698-4189-a192-de138c5c09d7)
![2024-12-26-07_46_18-screenshot](https://github.com/user-attachments/assets/b07fd3d2-76e1-4a2a-832f-7794e569eddf)

**Comment by blur131** [comment]
Why --no-daemon? What difference does it make?

**Comment by eladyn** [comment]
I finally got around to implementing OAuth support in `spotifyd`: #1321. It's become quite a large PR, so it's probably good to not merge it directly, but wait for some testing first. So if you've got the time to try the changes, that'd be very much appreciated!

**Comment by solarfl4re** [comment]
> I finally got around to implementing OAuth support in `spotifyd`: [#1321](https://github.com/Spotifyd/spotifyd/pull/1321). It's become quite a large PR, so it's probably good to not merge it directly, but wait for some testing first. So if you've got the time to try the changes, that'd be very much appreciated!

I installed spotifyd from my distro's repo and came to look at the issues here on Github when it gave me a "Bad credential" error. Checked out your PR and built it and it's working perfect; took me a minute to realize I needed to run `spotifyd auth`.

**Comment by eladyn** [comment]
Sounds like it, assuming hifiberry is using `spotifyd`. But I'm not really familiar with `hifiberry`, so take that with a grain of salt.

**Comment by RazoBeckett** [comment]
Can anyone suggest me a working fork of [spotify-tui](https://github.com/Rigellute/spotify-tui) because the search doesn't work in spotify_tui, and yeah don't suggest me any else like [spotify_player](https://github.com/aome510/spotify-player) or ncspot i don't like those.

**Comment by 5p4r70n** [comment]
> I just tried the credentials.json suggestion with librespot-auth as suggested by [@eladyn](https://github.com/eladyn), however the resulting credentials file contains just my usual username. So naturally I'm still stuck on the bad credentials error when trying to authenticate. Anyone else experiencing this issue?

Comment username and password from config file

**Comment by 5p4r70n** [comment]
official spotify client able to detect spotifyd but spotify-tui not able to detect. i used librespot-auth to configure spotifyd
