### ISSUE TITLE
Latest iOS Spotify update crashes spotifyd

### ISSUE THREAD

**Issue by wvangeit** [Spotifyd/spotifyd#134]
My phone updated my Spotify Music app to version 8.4.53 today. When I start the app, it crashes the spotifyd process on my server with the error below.

The Spotify app on my laptop can still communicate with spotifyd, as long as I don't start the app on my phone.

`
spotifyd[15647]: 19:19:17 [ERROR] Caught panic with message: called Result::unwrap() on an Err value: WireError(InvalidEnumValue(14))
systemd[1]: spotifyd.service: Main process exited, code=exited, status=101/n/a
systemd[1]: spotifyd.service: Unit entered failed state.
systemd[1]: spotifyd.service: Failed with result 'exit-code'.
`

**Comment by wvangeit** [comment]
(It happens both with an older version of spotifyd running on my server, and with a fresh compile based on the current master)

**Comment by wvangeit** [comment]
If you need a traceback:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WireError(InvalidEnumValue(14))', src/libcore/result.rs:916:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: std::panicking::begin_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::result::unwrap_failed
             at src/libcore/macros.rs:23
  10: <core::result::Result<T, E>>::unwrap
             at src/libcore/result.rs:782
  11: librespot_connect::spirc::Spirc::new::{{closure}}
             at /home/wvangeit/.cargo/git/checkouts/librespot-06fda9f186b35c32/817dff0/connect/src/spirc.rs:224
  12: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once
             at src/libcore/ops/function.rs:271
  13: <core::option::Option<T>>::map
             at src/libcore/option.rs:404
  14: <futures::stream::map::Map<S, F> as futures::stream::Stream>::poll
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/stream/map.rs:79
  15: <alloc::boxed::Box<S> as futures::stream::Stream>::poll
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/stream/mod.rs:139
  16: <librespot_connect::spirc::SpircTask as futures::future::Future>::poll
             at /home/wvangeit/.cargo/git/checkouts/librespot-06fda9f186b35c32/817dff0/connect/src/spirc.rs:309
  17: <&'a mut F as futures::future::Future>::poll
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/future/mod.rs:1022
  18: <spotifyd::main_loop::MainLoopState as futures::future::Future>::poll::{{closure}}
             at src/main_loop.rs:176
  19: <core::option::Option<T>>::map
             at src/libcore/option.rs:404
  20: <spotifyd::main_loop::MainLoopState as futures::future::Future>::poll
             at src/main_loop.rs:173
  21: <futures::task_impl::Spawn<T>>::poll_future_notify::{{closure}}
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/mod.rs:289
  22: <futures::task_impl::Spawn<T>>::enter::{{closure}}
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/mod.rs:363
  23: futures::task_impl::std::set
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/std/mod.rs:78
  24: <futures::task_impl::Spawn<T>>::enter
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/mod.rs:363
  25: <futures::task_impl::Spawn<T>>::poll_future_notify
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/mod.rs:289
  26: tokio_core::reactor::Core::run::{{closure}}::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.17/src/reactor/mod.rs:236
  27: <futures::future::lazy::Lazy<F, R>>::get
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/future/lazy.rs:64
  28: <futures::future::lazy::Lazy<F, R> as futures::future::Future>::poll
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/future/lazy.rs:82
  29: <futures::task_impl::Spawn<T>>::poll_future_notify::{{closure}}
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/mod.rs:289
  30: <futures::task_impl::Spawn<T>>::enter::{{closure}}
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/mod.rs:363
  31: futures::task_impl::std::set
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/std/mod.rs:78
  32: <futures::task_impl::Spawn<T>>::enter
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/mod.rs:363
  33: <futures::task_impl::Spawn<T>>::poll_future_notify
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/mod.rs:289
  34: <tokio::executor::current_thread::Entered<'a, P>>::block_on::{{closure}}
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.5/src/executor/current_thread/mod.rs:445
  35: <tokio::executor::current_thread::Borrow<'a, U>>::enter::{{closure}}::{{closure}}
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.5/src/executor/current_thread/mod.rs:657
  36: tokio::executor::current_thread::CurrentRunner::set_spawn
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.5/src/executor/current_thread/mod.rs:689
  37: <tokio::executor::current_thread::Borrow<'a, U>>::enter::{{closure}}
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.5/src/executor/current_thread/mod.rs:656
  38: <std::thread::local::LocalKey<T>>::try_with
             at src/libstd/thread/local.rs:377
  39: <std::thread::local::LocalKey<T>>::with
             at src/libstd/thread/local.rs:288
  40: <tokio::executor::current_thread::Borrow<'a, U>>::enter
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.5/src/executor/current_thread/mod.rs:655
  41: <tokio::executor::current_thread::Entered<'a, P>>::block_on
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.5/src/executor/current_thread/mod.rs:444
  42: tokio_core::reactor::Core::run::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.17/src/reactor/mod.rs:234
  43: tokio_timer::timer::handle::with_default::{{closure}}
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.1/src/timer/handle.rs:64
  44: <std::thread::local::LocalKey<T>>::try_with
             at src/libstd/thread/local.rs:377
  45: <std::thread::local::LocalKey<T>>::with
             at src/libstd/thread/local.rs:288
  46: tokio_timer::timer::handle::with_default
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.1/src/timer/handle.rs:56
  47: tokio_core::reactor::Core::run::{{closure}}::{{closure}}::{{closure}}
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.17/src/reactor/mod.rs:233
  48: tokio_executor::global::with_default::{{closure}}
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.2/src/global.rs:176
  49: <std::thread::local::LocalKey<T>>::try_with
             at src/libstd/thread/local.rs:377
  50: <std::thread::local::LocalKey<T>>::with
             at src/libstd/thread/local.rs:288
  51: tokio_executor::global::with_default
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.2/src/global.rs:150
  52: tokio_core::reactor::Core::run::{{closure}}::{{closure}}
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.17/src/reactor/mod.rs:232
  53: tokio_reactor::with_default::{{closure}}
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.1/src/lib.rs:207
  54: <std::thread::local::LocalKey<T>>::try_with
             at src/libstd/thread/local.rs:377
  55: <std::thread::local::LocalKey<T>>::with
             at src/libstd/thread/local.rs:288
  56: tokio_reactor::with_default
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.1/src/lib.rs:199
  57: tokio_core::reactor::Core::run::{{closure}}
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.17/src/reactor/mod.rs:231
  58: <scoped_tls::ScopedKey<T>>::set
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.1/src/lib.rs:155
  59: tokio_core::reactor::Core::run
             at /home/wvangeit/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.17/src/reactor/mod.rs:230
  60: spotifyd::main
             at src/main.rs:117
  61: std::rt::lang_start::{{closure}}
             at src/libstd/rt.rs:74
  62: std::panicking::try::do_call
  63: __rust_maybe_catch_panic
  64: std::rt::lang_start_internal
  65: std::rt::lang_start
             at src/libstd/rt.rs:74
  66: main
  67: __libc_start_main
  68: _start
```

**Comment by SimonPersson** [comment]
This issue is fixed by #135. Thanks for reporting.

**Comment by biocross** [comment]
@SimonPersson Did this fix the issue for you guys? I just download the latest tag, and I'm still getting this issue. Has this been tagged yet?

**Comment by wvangeit** [comment]
@biocross if you pull the latest master (75d46104fce826baa400b6be4bb2ee9e5b01bb55), it should work (at least it does for me). The latest commits pulls the latest librespot which contains this fix: https://github.com/librespot-org/librespot/pull/224

**Comment by biocross** [comment]
@wvangeit Oh, alright. I'm running this on a raspberry pi, so I can't compile on it since no rust support for the pi. Where I can find the prebuilt binary?

**Comment by SimonPersson** [comment]
I rebuilt the latest release, it should be fixed now.
