### ISSUE TITLE
Spotifyd not working on RPI

### ISSUE THREAD

**Issue by stevenveenma** [Spotifyd/spotifyd#139]
I downloaded the latest version and installed it. I can see it in Spotify connect, but it is not stable. Below the result of the logging. Something is failing in librespot, I thought it was not used any more? 

I have an additional question. I used to have a config file where the settings are made using quotes f.i. "entry". In the wiki I see an example where no quotes are used. I don't get any errors with or without quotes, so both can be used?

`sudo ./spotifyd --no-daemon --verbose
13:39:32 [TRACE] mio::poll: [<unknown>:785] registering with poller
13:39:32 [TRACE] tokio_threadpool::builder: [<unknown>:326] build; num-workers=4
13:39:32 [INFO] Using software volume controller.
13:39:32 [DEBUG] tokio_reactor::background: starting background reactor
13:39:32 [DEBUG] librespot_connect::discovery: Zeroconf server listening on 0.0.0.0:0
13:39:32 [TRACE] mio::poll: [<unknown>:785] registering with poller
13:39:32 [TRACE] mio::poll: [<unknown>:785] registering with poller
13:39:32 [TRACE] tokio_reactor: [<unknown>:345] event Writable Token(4194305)
13:39:32 [TRACE] mio::poll: [<unknown>:785] registering with poller
13:39:32 [DEBUG] tokio_reactor: loop process - 1 events, 0.000s
13:39:32 [TRACE] tokio_reactor: [<unknown>:345] event Writable Token(8388610)
13:39:32 [DEBUG] tokio_reactor: loop process - 1 events, 0.000s
13:39:32 [TRACE] mio::poll: [<unknown>:785] registering with poller
13:39:32 [TRACE] tokio_reactor: [<unknown>:345] event Writable Token(12582915)
13:39:32 [DEBUG] tokio_reactor: loop process - 1 events, 0.000s
13:39:32 [TRACE] hyper::client::pool: [<unknown>:125] park; waiting for idle connection: "http://apresolve.spotify.com"
13:39:32 [TRACE] hyper::client::connect: [<unknown>:118] Http::connect("http://apresolve.spotify.com/")
13:39:32 [DEBUG] hyper::client::dns: resolving host="apresolve.spotify.com", port=80
13:39:32 [DEBUG] tokio_core::reactor: consuming notification queue
13:39:32 [TRACE] mdns::fsm: [/root/.cargo/git/checkouts/rust-mdns-881ed19b93df0e9d/733b2b6/src/fsm.rs:275] sending packet to V4(224.0.0.251:5353)
13:39:32 [TRACE] tokio_reactor: [<unknown>:345] event Readable | Writable Token(4194305)
13:39:32 [DEBUG] tokio_reactor: loop process - 1 events, 0.000s
13:39:32 [TRACE] tokio_reactor: [<unknown>:345] event Readable | Writable Token(4194305)
13:39:32 [DEBUG] tokio_reactor: loop process - 1 events, 0.000s
13:39:32 [TRACE] tokio_reactor: [<unknown>:345] event Readable | Writable Token(4194305)
13:39:32 [DEBUG] tokio_reactor: loop process - 1 events, 0.000s
13:39:32 [TRACE] mdns::fsm: [/root/.cargo/git/checkouts/rust-mdns-881ed19b93df0e9d/733b2b6/src/fsm.rs:275] sending packet to V6([ff02::fb]:5353)
13:39:32 [TRACE] tokio_reactor: [<unknown>:345] event Readable | Writable Token(8388610)
13:39:32 [DEBUG] tokio_reactor: loop process - 1 events, 0.000s
13:39:32 [TRACE] tokio_reactor: [<unknown>:345] event Readable | Writable Token(8388610)
13:39:32 [DEBUG] tokio_reactor: loop process - 1 events, 0.000s
13:39:32 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 5420942 }
13:39:32 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 344, tv_nsec: 59088343 }
13:39:32 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 308750 }
13:39:32 [TRACE] mdns::fsm: [/root/.cargo/git/checkouts/rust-mdns-881ed19b93df0e9d/733b2b6/src/fsm.rs:76] received packet from V4(192.168.2.19:5353)
13:39:32 [TRACE] mdns::fsm: [/root/.cargo/git/checkouts/rust-mdns-881ed19b93df0e9d/733b2b6/src/fsm.rs:87] received packet from V4(192.168.2.19:5353) with no query
13:39:32 [TRACE] mdns::fsm: [/root/.cargo/git/checkouts/rust-mdns-881ed19b93df0e9d/733b2b6/src/fsm.rs:76] received packet from V4(192.168.2.19:5353)
13:39:32 [TRACE] mdns::fsm: [/root/.cargo/git/checkouts/rust-mdns-881ed19b93df0e9d/733b2b6/src/fsm.rs:87] received packet from V4(192.168.2.19:5353) with no query
13:39:32 [TRACE] mdns::fsm: [/root/.cargo/git/checkouts/rust-mdns-881ed19b93df0e9d/733b2b6/src/fsm.rs:76] received packet from V6([fe80::c60:1c9e:716e:6d31]:5353)
13:39:32 [TRACE] mdns::fsm: [/root/.cargo/git/checkouts/rust-mdns-881ed19b93df0e9d/733b2b6/src/fsm.rs:87] received packet from V6([fe80::c60:1c9e:716e:6d31]:5353) with no query
13:39:32 [TRACE] mdns::fsm: [/root/.cargo/git/checkouts/rust-mdns-881ed19b93df0e9d/733b2b6/src/fsm.rs:76] received packet from V6([fe80::c60:1c9e:716e:6d31]:5353)
13:39:32 [TRACE] mdns::fsm: [/root/.cargo/git/checkouts/rust-mdns-881ed19b93df0e9d/733b2b6/src/fsm.rs:87] received packet from V6([fe80::c60:1c9e:716e:6d31]:5353) with no query
13:39:32 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 1540314 }
13:39:32 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 344, tv_nsec: 61036990 }
13:39:32 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 272605 }
13:39:32 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 38698 }
13:39:32 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 344, tv_nsec: 61467616 }
13:39:32 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 208229 }
13:39:32 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 25443197 }
13:39:32 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 344, tv_nsec: 87289615 }
13:39:32 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 326407 }
13:39:32 [DEBUG] hyper::client::connect: connecting to 104.199.64.136:80
13:39:32 [TRACE] mio::poll: [<unknown>:785] registering with poller
13:39:32 [TRACE] tokio_reactor: [<unknown>:345] event Writable Token(16777220)
13:39:32 [DEBUG] tokio_reactor: loop process - 1 events, 0.000s
13:39:32 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 17671004 }
13:39:32 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 344, tv_nsec: 106066349 }
13:39:32 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 546459 }
13:39:32 [TRACE] hyper::proto::h1::conn: [<unknown>:311] read_keep_alive; is_mid_message=false
13:39:32 [TRACE] hyper::proto: [<unknown>:122] should_keep_alive(version=Http11, header=None) = true
13:39:32 [TRACE] hyper::proto::h1::role: [<unknown>:349] Client::encode has_body=false, method=None
13:39:32 [TRACE] hyper::proto::h1::io: [<unknown>:546] reclaiming write buf Vec
13:39:32 [DEBUG] hyper::proto::h1::io: flushed 47 bytes
13:39:32 [TRACE] hyper::proto::h1::conn: [<unknown>:627] flushed State { reading: Init, writing: KeepAlive, keep_alive: Busy, error: None, read_task: None }
13:39:32 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 1341147 }
13:39:32 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 344, tv_nsec: 108611351 }
13:39:32 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 224167 }
13:39:32 [TRACE] tokio_reactor: [<unknown>:345] event Readable | Writable Token(16777220)
13:39:32 [DEBUG] tokio_reactor: loop process - 1 events, 0.000s
13:39:32 [TRACE] hyper::proto::h1::conn: [<unknown>:187] Conn::read_head
13:39:32 [DEBUG] hyper::proto::h1::io: read 686 bytes
13:39:32 [TRACE] hyper::proto::h1::role: [<unknown>:254] Response.parse([Header; 100], [u8; 686])
13:39:32 [TRACE] hyper::proto::h1::role: [<unknown>:259] Response.parse Complete(268)
13:39:32 [TRACE] hyper::header: [<unknown>:355] maybe_literal not found, copying "Keep-Alive"
13:39:32 [TRACE] hyper::header: [<unknown>:355] maybe_literal not found, copying "Vary"
13:39:32 [DEBUG] hyper::proto::h1::io: parsed 9 headers (268 bytes)
13:39:32 [DEBUG] hyper::proto::h1::conn: incoming body is content-length (418 bytes)
13:39:32 [TRACE] hyper::proto: [<unknown>:133] expecting_continue(version=Http11, header=None) = false
13:39:32 [TRACE] hyper::proto: [<unknown>:122] should_keep_alive(version=Http11, header=Some(Connection([KeepAlive]))) = true
13:39:32 [TRACE] hyper::proto::h1::conn: [<unknown>:273] Conn::read_body
13:39:32 [TRACE] hyper::proto::h1::decode: [<unknown>:88] decode; state=Length(418)
13:39:32 [TRACE] hyper::proto::h1::conn: [<unknown>:627] flushed State { reading: Body(Length(0)), writing: KeepAlive, keep_alive: Busy, error: None, read_task: None }
13:39:32 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 18260484 }
13:39:32 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 344, tv_nsec: 127221210 }
13:39:32 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 150469 }
13:39:32 [TRACE] hyper::proto::h1::conn: [<unknown>:273] Conn::read_body
13:39:32 [TRACE] hyper::proto::h1::decode: [<unknown>:88] decode; state=Length(0)
13:39:32 [DEBUG] hyper::proto::h1::conn: incoming body completed
13:39:32 [TRACE] hyper::proto::h1::conn: [<unknown>:440] maybe_notify; read_from_io blocked
13:39:32 [TRACE] hyper::proto::h1::conn: [<unknown>:311] read_keep_alive; is_mid_message=false
13:39:32 [TRACE] hyper::proto::h1::conn: [<unknown>:627] flushed State { reading: Init, writing: Init, keep_alive: Idle, error: None, read_task: None }
13:39:32 [TRACE] hyper::client::pool: [<unknown>:301] pool dropped, dropping pooled ("http://apresolve.spotify.com")
13:39:32 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 927136 }
13:39:32 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 344, tv_nsec: 128602982 }
13:39:32 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 180937 }
13:39:32 [INFO] Connecting to AP "gew1-accesspoint-b-86b1.ap.spotify.com:4070"
13:39:32 [TRACE] mio::poll: [<unknown>:785] registering with poller
13:39:32 [TRACE] hyper::proto::h1::conn: [<unknown>:311] read_keep_alive; is_mid_message=false
13:39:32 [TRACE] hyper::proto::h1::dispatch: [<unknown>:400] client tx closed
13:39:32 [TRACE] hyper::proto::h1::conn: [<unknown>:873] State::close_read()
13:39:32 [TRACE] hyper::proto::h1::conn: [<unknown>:880] State::close_write()
13:39:32 [TRACE] hyper::proto::h1::conn: [<unknown>:627] flushed State { reading: Closed, writing: Closed, keep_alive: Disabled, error: None, read_task: None }
13:39:32 [TRACE] hyper::proto::h1::conn: [<unknown>:635] shut down IO
13:39:32 [TRACE] mio::poll: [<unknown>:905] deregistering handle with poller
13:39:32 [DEBUG] tokio_reactor: dropping I/O source: 4
13:39:32 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 936616 }
13:39:32 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 344, tv_nsec: 147376695 }
13:39:32 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 170208 }
13:39:32 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 21354 }
13:39:32 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 344, tv_nsec: 147649716 }
13:39:32 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 150104 }
13:39:32 [TRACE] tokio_reactor: [<unknown>:345] event Writable Token(20971525)
13:39:32 [DEBUG] tokio_reactor: loop process - 1 events, 0.000s
13:39:32 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 15567616 }
13:39:32 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 344, tv_nsec: 163444051 }
13:39:32 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 426042 }
13:39:32 [TRACE] tokio_reactor: [<unknown>:345] event Readable | Writable Token(20971525)
13:39:32 [DEBUG] tokio_reactor: loop process - 1 events, 0.000s
13:39:32 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 16630325 }
13:39:32 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 344, tv_nsec: 283822741 }
13:39:32 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 1076616 }
13:39:32 [TRACE] tokio_io::framed_write: [<unknown>:182] flushing framed transport
13:39:32 [TRACE] tokio_io::framed_write: [<unknown>:185] writing; remaining=116
13:39:32 [TRACE] tokio_io::framed_write: [<unknown>:202] framed transport flushed
13:39:32 [TRACE] tokio_reactor: [<unknown>:345] event Readable | Writable Token(20971525)
13:39:32 [DEBUG] tokio_reactor: loop process - 1 events, 0.000s
13:39:32 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 96759296 }
13:39:32 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 344, tv_nsec: 530599137 }
13:39:32 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 317240 }
13:39:32 [TRACE] tokio_reactor: [<unknown>:345] event Readable | Writable Token(20971525)
13:39:32 [DEBUG] tokio_reactor: loop process - 1 events, 0.000s
13:39:32 [TRACE] tokio_io::framed_read: [<unknown>:189] attempting to decode a frame
13:39:32 [TRACE] tokio_io::framed_read: [<unknown>:192] frame decoded from buffer
13:39:32 [TRACE] tokio_reactor: [<unknown>:345] event Readable | Writable Token(20971525)
13:39:32 [DEBUG] tokio_reactor: loop process - 1 events, 0.000s
13:39:32 [INFO] Authenticated as "2zr4ryfzfwl1zkwppdnj1km2d" !
13:39:32 [DEBUG] librespot_core::session: new Session[0]
13:39:32 [TRACE] tokio_reactor: [<unknown>:345] event Readable | Writable Token(20971525)
13:39:32 [DEBUG] tokio_reactor: loop process - 1 events, 0.000s
13:39:32 [DEBUG] librespot_connect::spirc: new Spirc[0]
13:39:32 [DEBUG] librespot::component: new MercuryManager
13:39:32 [DEBUG] librespot_playback::player: new Player[0]
13:39:32 [INFO] Using alsa sink
13:39:32 [DEBUG] librespot_connect::spirc: input volume:65535 to mixer: 65535
13:39:32 [TRACE] tokio_reactor: [<unknown>:345] event Readable | Writable Token(20971525)
13:39:32 [DEBUG] tokio_reactor: loop process - 1 events, 0.000s
13:39:32 [TRACE] tokio_reactor: [<unknown>:345] event Readable | Writable Token(20971525)
13:39:32 [DEBUG] tokio_reactor: loop process - 1 events, 0.000s
13:39:32 [TRACE] tokio_io::framed_read: [<unknown>:189] attempting to decode a frame
13:39:32 [TRACE] tokio_io::framed_read: [<unknown>:192] frame decoded from buffer
13:39:32 [DEBUG] librespot_core::session: Session[0] strong=3 weak=2
13:39:32 [TRACE] tokio_io::framed_read: [<unknown>:189] attempting to decode a frame
13:39:32 [TRACE] tokio_io::framed_read: [<unknown>:192] frame decoded from buffer
13:39:32 [TRACE] tokio_io::framed_read: [<unknown>:189] attempting to decode a frame
13:39:32 [TRACE] tokio_io::framed_read: [<unknown>:192] frame decoded from buffer
13:39:32 [TRACE] tokio_io::framed_read: [<unknown>:189] attempting to decode a frame
13:39:32 [TRACE] tokio_io::framed_read: [<unknown>:192] frame decoded from buffer
13:39:32 [INFO] Country: "NL"
13:39:32 [TRACE] tokio_io::framed_read: [<unknown>:189] attempting to decode a frame
13:39:32 [TRACE] tokio_io::framed_read: [<unknown>:189] attempting to decode a frame
13:39:32 [TRACE] tokio_io::framed_read: [<unknown>:192] frame decoded from buffer
13:39:32 [TRACE] tokio_io::framed_read: [<unknown>:189] attempting to decode a frame
13:39:32 [TRACE] tokio_io::framed_read: [<unknown>:192] frame decoded from buffer
13:39:32 [TRACE] tokio_io::framed_read: [<unknown>:189] attempting to decode a frame
13:39:32 [TRACE] tokio_io::framed_write: [<unknown>:182] flushing framed transport
13:39:32 [TRACE] tokio_io::framed_write: [<unknown>:185] writing; remaining=400
13:39:32 [TRACE] tokio_io::framed_write: [<unknown>:202] framed transport flushed
13:39:32 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 2782033 }
13:39:32 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 344, tv_nsec: 536119037 }
13:39:32 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 182552 }
13:39:32 [TRACE] tokio_reactor: [<unknown>:345] event Readable | Writable Token(20971525)
13:39:32 [DEBUG] tokio_reactor: loop process - 1 events, 0.000s
13:39:32 [TRACE] tokio_io::framed_read: [<unknown>:189] attempting to decode a frame
13:39:32 [TRACE] tokio_io::framed_read: [<unknown>:192] frame decoded from buffer
13:39:32 [TRACE] tokio_io::framed_read: [<unknown>:189] attempting to decode a frame
13:39:32 [TRACE] tokio_io::framed_write: [<unknown>:182] flushing framed transport
13:39:32 [TRACE] tokio_io::framed_write: [<unknown>:202] framed transport flushed
13:39:32 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 14288241 }
13:39:32 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 344, tv_nsec: 550687903 }
13:39:32 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 199531 }
13:39:32 [TRACE] tokio_reactor: [<unknown>:345] event Readable | Writable Token(20971525)
13:39:32 [DEBUG] tokio_reactor: loop process - 1 events, 0.000s
13:39:32 [TRACE] tokio_io::framed_read: [<unknown>:189] attempting to decode a frame
13:39:32 [TRACE] tokio_io::framed_read: [<unknown>:192] frame decoded from buffer
13:39:32 [TRACE] tokio_io::framed_read: [<unknown>:189] attempting to decode a frame
13:39:32 [TRACE] tokio_io::framed_read: [<unknown>:192] frame decoded from buffer
13:39:32 [TRACE] tokio_io::framed_read: [<unknown>:189] attempting to decode a frame
13:39:32 [TRACE] tokio_io::framed_read: [<unknown>:192] frame decoded from buffer
13:39:32 [TRACE] tokio_io::framed_read: [<unknown>:189] attempting to decode a frame
13:39:32 [TRACE] tokio_io::framed_read: [<unknown>:192] frame decoded from buffer
13:39:32 [DEBUG] librespot_core::mercury: unknown subscription uri=hm://remote/3/user/2zr4ryfzfwl1zkwppdnj1km2d/bf59f7c37a1aa42b711baa43b8a1e5949d8e95f7
13:39:32 [TRACE] tokio_io::framed_read: [<unknown>:189] attempting to decode a frame
13:39:32 [TRACE] tokio_io::framed_write: [<unknown>:182] flushing framed transport
13:39:32 [TRACE] tokio_io::framed_write: [<unknown>:202] framed transport flushed
13:39:32 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 47422798 }
13:39:32 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 344, tv_nsec: 598408462 }
13:39:32 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 160365 }
13:39:32 [DEBUG] librespot_core::mercury: subscribed uri=hm://remote/3/user/2zr4ryfzfwl1zkwppdnj1km2d/ count=0
13:39:32 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 19271 }
13:39:32 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 344, tv_nsec: 598888931 }
13:39:32 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 165313 }
13:39:37 [TRACE] tokio_reactor: [<unknown>:345] event Readable | Writable Token(20971525)
13:39:37 [DEBUG] tokio_reactor: loop process - 1 events, 0.000s
13:39:37 [TRACE] tokio_io::framed_read: [<unknown>:189] attempting to decode a frame
13:39:37 [TRACE] tokio_io::framed_read: [<unknown>:189] attempting to decode a frame
13:39:37 [TRACE] tokio_io::framed_read: [<unknown>:192] frame decoded from buffer
13:39:37 [TRACE] tokio_io::framed_read: [<unknown>:189] attempting to decode a frame
13:39:37 [TRACE] tokio_io::framed_write: [<unknown>:182] flushing framed transport
13:39:37 [TRACE] tokio_io::framed_write: [<unknown>:202] framed transport flushed
13:39:37 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 4, nanos: 882929809 }
13:39:37 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 349, tv_nsec: 482064365 }
13:39:37 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 475053 }
13:39:37 [ERROR] Caught panic with message: called `Result::unwrap()` on an `Err` value: WireError(InvalidEnumValue(14))
13:39:37 [DEBUG] librespot_connect::spirc: drop Spirc[0]
13:39:37 [DEBUG] librespot_playback::player: Shutting down player thread ...
13:39:37 [DEBUG] librespot_playback::player: drop Player[0]
13:39:37 [DEBUG] librespot_core::session: drop Session[0]
13:39:37 [DEBUG] librespot::component: drop MercuryManager
13:39:37 [TRACE] tokio_threadpool::inner: [<unknown>:64] shutdown; state=State { lifecycle: 0, num_futures: 0 }
13:39:37 [TRACE] tokio_threadpool::inner: [<unknown>:110]   -> transitioned to shutdown
13:39:37 [TRACE] tokio_threadpool::inner: [<unknown>:122]   -> shutting down workers
13:39:37 [TRACE] tokio_threadpool::inner: [<unknown>:126]   -> shutdown worker; idx=3; state=WorkerState { lifecycle: "WORKER_SHUTDOWN", is_pushed: true }
13:39:37 [TRACE] tokio_threadpool::inner: [<unknown>:141] signal_stop -- WORKER_SHUTDOWN; idx=3
13:39:37 [TRACE] tokio_threadpool::inner: [<unknown>:176] worker_terminated; num_workers=3
13:39:37 [TRACE] tokio_threadpool::inner: [<unknown>:126]   -> shutdown worker; idx=2; state=WorkerState { lifecycle: "WORKER_SHUTDOWN", is_pushed: true }
13:39:37 [TRACE] tokio_threadpool::inner: [<unknown>:141] signal_stop -- WORKER_SHUTDOWN; idx=2
13:39:37 [TRACE] tokio_threadpool::inner: [<unknown>:176] worker_terminated; num_workers=2
13:39:37 [TRACE] tokio_threadpool::inner: [<unknown>:126]   -> shutdown worker; idx=1; state=WorkerState { lifecycle: "WORKER_SHUTDOWN", is_pushed: true }
13:39:37 [TRACE] tokio_threadpool::inner: [<unknown>:141] signal_stop -- WORKER_SHUTDOWN; idx=1
13:39:37 [TRACE] tokio_threadpool::inner: [<unknown>:176] worker_terminated; num_workers=1
13:39:37 [TRACE] tokio_threadpool::inner: [<unknown>:126]   -> shutdown worker; idx=0; state=WorkerState { lifecycle: "WORKER_SHUTDOWN", is_pushed: true }
13:39:37 [TRACE] tokio_threadpool::inner: [<unknown>:141] signal_stop -- WORKER_SHUTDOWN; idx=0
13:39:37 [TRACE] tokio_threadpool::inner: [<unknown>:176] worker_terminated; num_workers=0
13:39:37 [TRACE] tokio_threadpool::inner: [<unknown>:179] notifying shutdown task
13:39:37 [TRACE] tokio_threadpool::shutdown: [<unknown>:38] Shutdown::poll
13:39:37 [TRACE] tokio_reactor: [<unknown>:345] event Readable Token(4194303)
13:39:37 [DEBUG] tokio_reactor: loop process - 1 events, 0.000s
13:39:37 [DEBUG] tokio_reactor::background: shutting background reactor down NOW
13:39:37 [DEBUG] tokio_reactor::background: background reactor has shutdown
13:39:37 [DEBUG] librespot_core::session: drop Dispatch

`

**Comment by captnbp** [comment]
Hi,

I have the same issue on my RPi using the binary from 2018-04-03 and the last one 2018-05-03:
```
09:56:18 [DEBUG] hyper::proto::h1::io: flushed 507 bytes
09:56:18 [TRACE] hyper::proto::h1::conn: [<unknown>:440] maybe_notify; read_from_io blocked
09:56:18 [TRACE] hyper::proto::h1::conn: [<unknown>:627] flushed State { reading: Init, writing: Init, keep_alive: Idle, error: None, read_task: Some(Task) }
09:56:18 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 45243963 }
09:56:18 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 513, tv_nsec: 226610967 }
09:56:18 [DEBUG] tokio_core::reactor: loop process, Duration { secs: 0, nanos: 3141928 }
09:56:18 [ERROR] Caught panic with message: called `Result::unwrap()` on an `Err` value: WireError(InvalidEnumValue(14))
```

**Comment by SimonPersson** [comment]
This issue is fixed by #135. Thanks for reporting.

**Comment by FungusHumungus** [comment]
I don't think it has. I am still getting this error with the latest release (2018-05-22).

**Comment by SimonPersson** [comment]
Can you try again? I launched a new build, and the latest one seems to work on x86 at least.

**Comment by FungusHumungus** [comment]
Yes, that seems to have fixed it. Working beautifully again. Thanks!

**Comment by stevenveenma** [comment]
Having raised this issue I can confirm that it is solved now, thanks!

It took me some time to enable the automatic start when booting the RPI using systemctl. I expected that just replacing the spotifyd file on the same location should be sufficient, but this is not the case. At the end I discovered that disabling the old service and repeating the steps in the wiki solved it.
