### ISSUE TITLE
Unable to set spotify player to repeat song

### ISSUE THREAD

**Issue by juliangaal** [Spotifyd/spotifyd#381]
I'm unable to set song to repeat/endless loop. Tried to restart the app, and daemon, no effect. Can you reproduce the issue? 

client: iOS 12.4.1
spotifyd: ubuntu 18.04

Is this issue relevant for [this](https://github.com/Spotifyd/spotifyd/projects/2), maybe?

Thanks

**Comment by SirWindfield** [comment]
If it is related, you'd have to select a song, start to play it over the daemon and skip for example from the phone. Setting the repeat should now work if it's the same problem.

**Comment by juliangaal** [comment]
With `repeat` I mean setting [the little icon like so](https://imgur.com/gallery/aayjsM3)

Not sure what you mean with skip. If I skip the song and try setting repeat, I still have the same problem: it just won't set itself to the icon I linked above

**Comment by SirWindfield** [comment]
Ah ok, I thought you'd use DBus commands to set it on repeat. I will test this on the weekend and see if I can find some bug :)

**Comment by juliangaal** [comment]
Must have been fixed with the recent bump in librespot version! Works again on current master branch

**Comment by SirWindfield** [comment]
Thanks for letting me know!

**Comment by juliangaal** [comment]
any ETA until the next release? I can't quite get this thing to cross compile, and the master fixed two bugs I depended on (repeat, discovery mode). Would make things easier ;)

**Comment by SirWindfield** [comment]
Which machine are you compiling for? I didn't get to implement all changes/fixes I wanted for the new release but those aren't that important anyway.

I can probably push a new release this evening. Make sure to watch the repo to get a Github notification :)

**Comment by juliangaal** [comment]
raspberry pi zero

steps I took:
* cloned the repo
* edited `.cargo/config` with
```bash
[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc-7"
```
* `openssl` wasn't found, so had to add this line to `[dev-dependencies]`: `openssl = { version = "0.10", features = ["vendored"] }`
* compiled with `cargo build --target=armv7-unknown-linux-gnueabihf --release`, but getting error
```bash
error: linking with `arm-linux-gnueabihf-gcc-7` failed: exit code: 1
  |
  = note: "arm-linux-gnueabihf-gcc-7" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-L" "/home/juliangaal/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/spotifyd-a1a9bd9e604d9e3f.spotifyd.90srqu0q-cgu.0.rcgu.o" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/spotifyd-a1a9bd9e604d9e3f.spotifyd.90srqu0q-cgu.1.rcgu.o" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/spotifyd-a1a9bd9e604d9e3f.spotifyd.90srqu0q-cgu.10.rcgu.o" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/spotifyd-a1a9bd9e604d9e3f.spotifyd.90srqu0q-cgu.11.rcgu.o" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/spotifyd-a1a9bd9e604d9e3f.spotifyd.90srqu0q-cgu.12.rcgu.o" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/spotifyd-a1a9bd9e604d9e3f.spotifyd.90srqu0q-cgu.13.rcgu.o" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/spotifyd-a1a9bd9e604d9e3f.spotifyd.90srqu0q-cgu.14.rcgu.o" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/spotifyd-a1a9bd9e604d9e3f.spotifyd.90srqu0q-cgu.15.rcgu.o" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/spotifyd-a1a9bd9e604d9e3f.spotifyd.90srqu0q-cgu.2.rcgu.o" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/spotifyd-a1a9bd9e604d9e3f.spotifyd.90srqu0q-cgu.3.rcgu.o" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/spotifyd-a1a9bd9e604d9e3f.spotifyd.90srqu0q-cgu.4.rcgu.o" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/spotifyd-a1a9bd9e604d9e3f.spotifyd.90srqu0q-cgu.5.rcgu.o" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/spotifyd-a1a9bd9e604d9e3f.spotifyd.90srqu0q-cgu.6.rcgu.o" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/spotifyd-a1a9bd9e604d9e3f.spotifyd.90srqu0q-cgu.7.rcgu.o" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/spotifyd-a1a9bd9e604d9e3f.spotifyd.90srqu0q-cgu.8.rcgu.o" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/spotifyd-a1a9bd9e604d9e3f.spotifyd.90srqu0q-cgu.9.rcgu.o" "-o" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/spotifyd-a1a9bd9e604d9e3f" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/spotifyd-a1a9bd9e604d9e3f.3zgt5idhudf68jjf.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps" "-L" "/home/juliangaal/dev/spotifyd/target/release/deps" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/build/backtrace-sys-96a1b7c67d854008/out" "-L" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/build/tremor-sys-12d9ac386190fb7a/out" "-L" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/build/ogg-sys-3a1146b8b0885721/out" "-L" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/build/openssl-sys-2a59ef10b085c8c3/out/openssl-build/install/lib" "-L" "/home/juliangaal/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib" "-Wl,-Bstatic" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libsyslog-26d705a7037c8ca5.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/liberror_chain-dc347ed1bcde029f.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libhex-6d7c60b426bbbe52.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libserde_ini-803e39c795a9e6ff.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libresult-81859d67164d10d4.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libwhoami-0e1b91daddb7592c.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libtokio_signal-a13f4b1732aa5a39.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libxdg-1c518c50af2c388f.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libgethostname-8aa220eac443bf5f.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/liblibrespot-26931c7c3c1a1439.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/liblibrespot_connect-ed74c776c1edc669.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/liblibrespot_playback-816cad7c96d231ff.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/liblibrespot_metadata-716b83620f5f6f0b.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/liblinear_map-d976bb549f71d347.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libalsa-6753179710d742e8.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libnix-d0184310bfc1a14b.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libmdns-32e5d3a360f2d054.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libnix-e296a7b740f4fef6.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libmultimap-5b5b2ada1035fc04.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libget_if_addrs-7ee504381a0fa2f5.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libc_linked_list-75f31a5a2e4ad76e.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libdns_parser-c152f4012a268318.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libquick_error-ae20398b2d56a7bc.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libbyteorder-1ca9ecd7c646f06b.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libblock_modes-6be256c4960823c7.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/liblibrespot_audio-6e778f88ece60ce5.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libtremor-f3a86933eadf45dc.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libtremor_sys-c3f80a8759ffb2db.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libogg_sys-e6024818671fa640.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/liblibrespot_core-135306c1723a6314.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/liblibrespot_protocol-15069b9031a80764.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libaes-b0465fba24b88400.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libpbkdf2-c76ea3b3fb26044a.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libsha2-d280c8fcf63e103a.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/librand-8bcc78f04943960a.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libhmac-debe08934948e864.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libcrypto_mac-8c90a67b778b109d.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libsubtle-f65eddc962e388c9.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libsha1-42703cefa6e1aebc.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libfake_simd-65e609d4d94701fc.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libdigest-7c93236ddb7c2f0f.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libblock_buffer-c7aa06248561e521.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libblock_padding-a454d91bf76d7fb5.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libbyte_tools-adde063636375107.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libuuid-58bf61d2582fb4ea.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libshannon-16b044311c48520d.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libserde_json-cfe9e3db4af77639.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libryu-aeb64eba0cdc4f7f.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libitoa-c4e7bdc8356e466e.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libhyper_proxy-2381c4ad1bc8f0db.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libextprim-165fdea4120e57c6.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/liberror_chain-72011d16e45a4bc0.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libbacktrace-e6eb7c2f22a4f18f.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libbacktrace_sys-be61f164a04c626b.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/librustc_demangle-ac0772ed06bd66c4.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libaes_ctr-dc4ed2373d7e3f7a.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libaes_soft-10c568de2974116b.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libopaque_debug-00beeb73b30c066e.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libctr-243fa10debbbfab1.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libblock_cipher_trait-7cce464b9c79c914.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libstream_cipher-1b869c4d4d227f43.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libgeneric_array-a7966ed8724aebec.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libtypenum-d7880e5857a70b6c.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libtempfile-e379ec8480ffc0be.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libremove_dir_all-015596256cc9b2ce.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libbit_set-f9bafeb893370c97.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libbit_vec-e517ef57fc69b081.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/liburl-1a790b10810e75b3.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libidna-8b9bcda7bbdeb576.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libunicode_normalization-0c8e08daf859dd56.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libunicode_bidi-db9e6be2b6fb9732.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libmatches-3e5c16c291f4c99b.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/librand-38bf0da8272418c2.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/librand_chacha-cca8074233b271fa.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libc2_chacha-4d10800789e3db97.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libppv_lite86-4f3f2e12c6fbadae.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/librand_core-aa823f6020aa2419.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libgetrandom-2cca8a94a413b271.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libprotobuf-4aa3f11b214d11a2.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libnum_bigint-183d7934c7ca5770.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libhyper-4d0eb9dc3482e133.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libwant-b21462e001f52cc0.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libtry_lock-1aa439139df5c77e.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libunicase-1cf75a1428e8e6f0.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libtokio_proto-ae504b569a50a323.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/liblog-90c2f9f024c5cdca.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libtokio_service-bc244095dd47a13c.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libtake-93f83ea1ed1b74d0.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libsmallvec-ec2e2b9b8707b821.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libslab-f754aa9b21793272.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/librand-03031697200e7eca.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/librand-4ded29de299a5c39.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/librelay-ccaada064b1f2ea7.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libpercent_encoding-6ddd870dd9d33ce4.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libmime-251f96d00e360920.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/liblanguage_tags-33712938add633bd.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libhttparse-4a5ba059ff2c8d0b.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libfutures_cpupool-3c13e546dbbe71b4.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libbase64-647b83acca163e1d.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libsafemem-5811997c0cbd2d56.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libbase64-358344ded8c95b31.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libalsa-928b56dec50d6267.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libnix-4cf119722ffecd39.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libvoid-5626585061ec4070.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libbitflags-c47633d3c1ebf302.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libalsa_sys-861a2c3d5274027c.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libtokio_core-223a6c260037ae0e.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libscoped_tls-fdbbacc1407a14b7.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libtokio-485f1ac268906a15.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libtokio_uds-af1e7b28ac11bb0b.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libmio_uds-0e3a053d60d1e166.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libtokio_udp-fd93f333119a48e5.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libtokio_timer-e0db249e27a6d0b2.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libtokio_tcp-0a4c7b8efcd40b9e.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libtokio_reactor-f661fd00ad084e97.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libtokio_sync-277adb27a9f2c24a.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libfnv-191f47240ed684ea.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libparking_lot-0a58a989fa3260be.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libparking_lot_core-09e437262349ab81.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libsmallvec-d5987b73c22113c1.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/liblock_api-fd885275ad775cef.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libowning_ref-95adfee4784653a4.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libstable_deref_trait-b9a4712896c1a79a.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libscopeguard-1e4fa3e1b5bc5571.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libtokio_fs-e2790bfce00088ad.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libtokio_threadpool-e4601c5b10cbab88.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/librand-5597c2e3dc7fc260.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/librand_xorshift-eeaa0c601c24fdf7.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/librand_pcg-a3b623e8cc4d313c.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/librand_hc-fa0ba83696d2582d.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/librand_chacha-f54d0cba28739355.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/librand_isaac-c2c2d8f907e540f9.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/librand_core-05c564e392cca394.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/librand_os-0c766fea4f77f6a8.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/librand_jitter-28b98961f2b5af09.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/librand_core-ad4facc9c9e981a1.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libcrossbeam_queue-f2680ef53caef3dc.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libcrossbeam_deque-49d082ba86429643.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libcrossbeam_epoch-885187f599d4e124.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libscopeguard-8ef33c09dcfe8ff0.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libmemoffset-457f22c8bf8c2bb9.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libarrayvec-410f5890e0524738.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libnodrop-9ea8a58bfc34328b.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libtokio_current_thread-0b122b4005f50195.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libtokio_executor-39850ab8eef6e7c2.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libcrossbeam_utils-9d9e5f6876c0035b.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/liblazy_static-7e7a626d2a5feeb8.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libtokio_codec-15c0638e89f318cd.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libtokio_io-fb765994efe7a1ed.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libnum_cpus-1fdcf26c3c7baa4f.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libmio-1bb70955541759fe.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libslab-fdb08aac8a6c142b.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libnet2-a18065ef6c9160ce.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libfutures-f683e4916804b4ad.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libbytes-2d0d6a3dbc76d486.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libeither-38812672bdb31fad.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libiovec-1b90384d4ab86c10.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libbyteorder-e72e001f0a03a9f4.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libstructopt-3816b0c75c388c34.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libclap-ff79c80b7af968c8.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libvec_map-0dafdb2ea8511067.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libtextwrap-8afb5ec3dd24849e.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libunicode_width-661c8faad4914368.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libstrsim-2886591d947dfac8.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libbitflags-f3016fbac3bf316c.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libatty-83385f3b684b2be2.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libansi_term-0e7f07fa3280f563.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libsimplelog-dbd04f6ebfcd12bf.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libterm-34d6000735b3f5d7.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libdirs-c6f779ca5faccfdb.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libdirs_sys-3824d3b6b5839b67.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libchrono-b4d63315f9a7277b.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libserde-33bb7e5e49dbb722.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/librustc_serialize-b43794dc0a0fcbc7.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libnum_integer-1b28dd7f6e990ea7.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libnum_traits-f21e8f13d4868d9e.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libtime-0d94ca4b11bbbaa2.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/liblog-b9f9346a2a50a91c.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libcfg_if-0e9a6a3d1e7f52e1.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libdaemonize-d66b95339abdc077.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/libboxfnonce-0e9aed9f0426d900.rlib" "/home/juliangaal/dev/spotifyd/target/armv7-unknown-linux-gnueabihf/release/deps/liblibc-8fc83ed7258405a6.rlib" "-Wl,--start-group" "/home/juliangaal/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/libstd-2dc1ba48239659d3.rlib" "/home/juliangaal/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/libpanic_unwind-57306b8ed3378a0e.rlib" "/home/juliangaal/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/libbacktrace_sys-54463ae5adae3649.rlib" "/home/juliangaal/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/librustc_demangle-d99667b199a9875a.rlib" "/home/juliangaal/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/libhashbrown-51f4300e102199f5.rlib" "/home/juliangaal/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/librustc_std_workspace_alloc-b3ccf1f7737a6a91.rlib" "/home/juliangaal/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/libunwind-157c37a3ceb78853.rlib" "/home/juliangaal/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/liblibc-505bcee45aafb736.rlib" "/home/juliangaal/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/liballoc-c29abd529ba4452b.rlib" "/home/juliangaal/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/librustc_std_workspace_core-895383a3232f6572.rlib" "/home/juliangaal/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/libcore-5594cb4f559bc761.rlib" "-Wl,--end-group" "/home/juliangaal/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/libcompiler_builtins-38e90baf978bc428.rlib" "-Wl,-Bdynamic" "-lasound" "-lutil" "-lutil" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-lutil"
  = note: /usr/lib/x86_64-linux-gnu/libasound.so: file not recognized: File format not recognized
          collect2: error: ld returned 1 exit status
```

which suggests `libasound-dev` issues, but it is installed and working, as I can start a local spotifyd instance on my laptop

**Comment by juliangaal** [comment]
any update on the next release? ;)

**Comment by SirWindfield** [comment]
Sorry, been busy the last days. I've got off tomorrow so I can push a new release, promised :l

**Comment by marianopw** [comment]
Any update on this? I'm receiving the same error

**Comment by louy2** [comment]
Same, cannot set Repeat Track, is this a regression?

**Comment by PikaFan123** [comment]
Im having this issue too.

OS: Arch Linux
Client: Ive tried spotify-tui, the official client and Spotify Android
Version: spotifyd 0.3.3

**Comment by owenrummage** [comment]
Any update? Really sucks not being able to repeat songs :(
